- name: Demo for conditional installation - installing,config and deployment of webpage to nginx web server 
  hosts: all
  vars: 
   - greeting_msg: Devops
   - provitioner_tool: Docker
   - automation_tool: Ansible  
  tasks: 
   #This is a comment
   - name: Install nginx web server in Ubuntu
     when: (ansible_distribution == "Ubuntu" and ansible_os_family == "Debian")
     apt: 
       name: nginx 
       state: latest 
       update_cache: yes

   - name: Install EPEL (Extra Package for Enterprise Linux) in CentOS
     when: (ansible_distribution == "CentOS" and ansible_os_family == "RedHat")
     yum: name=epel-release state=latest

   - name: Install nginx web server in CentOS
     when: (ansible_distribution == "CentOS" and ansible_os_family == "RedHat")
     yum: 
       name: nginx 
       state: latest 
       #update_cache: yes
   
   - name: Configure nginx web root folder in Ubuntu 
     when: (ansible_distribution == "Ubuntu" and ansible_os_family == "Debian")
     copy: src=default dest=/etc/nginx/sites-available/default
   
   - name: Configure nginx web root folder in CentOS 
     when: (ansible_distribution == "CentOS" and ansible_os_family == "RedHat")
     copy: src=default.conf dest=/etc/nginx/conf.d/default.conf

   - name: Restart the nginx server
     command: service nginx restart

   - name: Create the web root folder
     file: path=/var/html state=directory mode=0777

   - name: Deploy a web page into nginx web server
     template: src=index.html.j2 dest=/var/html/index.html 
     #when: (ansible_distribution == "Ubuntu" and ansible_os_family == "Debian")
